<section data-translation="true">
	<h1>Welcome to uqunie.com</h1>
</section>

<section>
	<h1>NEWS</h1>
	<section>
		<h2 data-translation="true">We are establishing a new Hokuriku office</h2>
		<span class="float right">2026-04-12</span>
		<p data-translation="true">
			In preparation for unforeseen incidents such as a major metropolitan earthquake or a fire at our Tokyo headquarters, we have decided to establish a new office in a remote location.
		</p>
		<p data-translation="true">
			We are currently recruiting individuals who are willing to work at the Hokuriku office. If you are interested, please contact us through the inquiry form.
		</p>
		<hr/>
		<h2 data-translation="true">Our website has been renewed</h2>
		<span class="float right">2026-04-01</span>
		<p data-translation="true">
			The ONEPIECE Framework version has been updated from "2024" to "2030".
		</p>
	</section>
</section>

<!-- Translation Service -->
<?php OP()->Template('translation.phtml') ?>
